import { Injectable } from '@angular/core';
import { User, UserFactory } from '@shared/objects';
import { StorageService } from '@shared/services';
import { generateIdentifier } from '@globals';
import * as uuidv4 from 'uuid/v4';

/**
* This service manages the state of the user of this application.
* @author Rob Miller
* @copyright 2018
*/
@Injectable()
export class UserService {
  constructor(public storageService: StorageService) {
    this.loadUser();
  }

  /**
  * Loads a user from local storage or creates a new one if no user exists
  */
  private async loadUser() {
    let user: User = await this.storageService.get('user');

    if (!user) {
      user = UserFactory.createUser("Anonymous", uuidv4());
    }

    this.storageService.set('user', user);
  }

  /**
  * Returns the user object from local storage
  */
  private async getUser() {
    return this.storageService.get('user');
  }

  /**
  * Sets the name on the local user
  * @param name
  */
  public async setName(name: string) {
    let user: User = await this.getUser();
    user.name = name;
    this.storageService.set('user', user);
  }

  /**
  * Gets the name from local storage
  * @return user name
  */
  public async getName() {
    let user: User = await this.storageService.get('user');
    return user.name;
  }

  /**
  * Gets the id from local storage
  * @return user id
  */
  public async getId() {
    let user: User = await this.storageService.get('user');
    return user.id;
  }

  /**
  * Builds an id from the user in local storage
  * @return user identifier
  */
  public async getIdentifier() {
    let user: User = await this.storageService.get('user');
    return generateIdentifier(user.name, user.id, user.endpoint);
  }

  /**
  * Gets the endpoint id from local storage
  * @return endpoint id
  */
  public async getEndpoint() {
    let user: User = await this.storageService.get('user');
    return user.endpoint;
  }

  /**
  * Sets the endpoint id on the user
  * @param ep the endpoint id generated by Nearby
  */
  public async setEndpoint(ep: string) {
    let user: User = await this.storageService.get('user');
    user.endpoint = ep;
    this.storageService.set('user', user);
  }
}
